install:
	install cpu*.svg $(DESTDIR)/usr/share/icons/hicolor/scalable/actions/
	install pardus-pm*.svg $(DESTDIR)/usr/share/icons/hicolor/scalable/actions/
	install main.ui $(DESTDIR)/usr/lib/pardus/power-manager/
	install main.css $(DESTDIR)/usr/lib/pardus/power-manager/
	install status/*.svg $(DESTDIR)/usr/share/icons/hicolor/scalable/actions/
	install pardus-power-manager.svg $(DESTDIR)/usr/share/icons/hicolor/scalable/apps/
