install:
	install *.svg $(DESTDIR)/usr/share/icons/hicolor/scalable/actions
	install main.ui $(DESTDIR)/usr/lib/pardus/power-manager/
	install main.css $(DESTDIR)/usr/lib/pardus/power-manager/
	install status/*.svg $(DESTDIR)/usr/share/icons/hicolor/scalable/actions
