install:
	install start-window.sh $(DESTDIR)/usr/lib/pardus/power-manager/
	install pardus-power-manager.desktop $(DESTDIR)/usr/share/applications/
	install pardus-power-manager.policy $(DESTDIR)/usr/share/polkit-1/actions
