install:
	install pardus-power-manager.desktop $(DESTDIR)/usr/share/applications/
	install pardus-power-manager.desktop $(DESTDIR)/etc/xdg/autostart/
	install pardus-power-manager.policy $(DESTDIR)/usr/share/polkit-1/actions
	install pardus-power-manager.svg $(DESTDIR)/usr/share/icons/hicolor/scalable/apps/
