install:
	install main.py $(DESTDIR)/usr/lib/pardus/power-manager/
	install cpu.py $(DESTDIR)/usr/lib/pardus/power-manager/
	install cpucli.py $(DESTDIR)/usr/lib/pardus/power-manager/
	install setprofile.py $(DESTDIR)/usr/lib/pardus/power-manager/
	ln -s ../lib/pardus/power-manager/main.py $(DESTDIR)/usr/bin/pardus-power-manager || true