install:
	install main.css $(DESTDIR)/usr/lib/pardus/power-manager/
	install main.py $(DESTDIR)/usr/lib/pardus/power-manager/
	install main.ui $(DESTDIR)/usr/lib/pardus/power-manager/
	install setprofile.py $(DESTDIR)/usr/lib/pardus/power-manager/
	ln -s ../lib/pardus/power-manager/main.py $(DESTDIR)/usr/bin/pardus-power-manager || true